version: '3.7'

services:

  oneof-application:
    container_name: oneof
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_PORT}:${NGINX_PORT}"
    volumes:
      - ./src/environments:/usr/local/app/environments